BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS user_data (
    id VARCHAR(20) PRIMARY KEY,
    ketchup INT NOT NULL DEFAULT 0,
    last_daily INT NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS reminders;
CREATE TABLE IF NOT EXISTS reminders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id VARCHAR(20) NOT NULL,
    message VARCHAR(255) NOT NULL,
    timestamp INTEGER NOT NULL
);

COMMIT;
