name = "ketchup-bot"
main = "./dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID

[[d1_databases]]
binding = "DB"
database_name = "ketchup-bot"
database_id = "bdc65bc6-2d8e-43a2-88c6-4b0ee8642506"

[[kv_namespaces]]
binding = "KV"
id = "88ed17f6ed6c44e9b5c6fd763bf7bffa"

[[workflows]]
name = "reminders-workflow"
binding = "REMINDERS_WORKFLOW"
class_name = "RemindersWorkflow"

[observability.logs]
enabled = true
