name: ESLint

on: [push, pull_request]

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: Install Yarn
              uses: borales/actions-yarn@v4
              with:
                cmd: install --immutable

            - name: Run ESLint
              run: yarn eslint
